apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-worker
  namespace: query-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trino-worker
  template:
    metadata:
      labels:
        app: trino-worker
    spec:
      containers:
      - name: trino-worker
        image: trinodb/trino:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/trino
          name: trino-config
      volumes:
      - name: trino-config
        configMap:
          name: trino-worker-config
