apiVersion: v1
kind: Secret
metadata:
  name: trino-credentials
  namespace: query-engine
type: Opaque
data:
  MINIO_ACCESS_KEY: YWRtaW4= # admin
  MINIO_SECRET_KEY: YWRtaW4xMjM= # admin123

  AWS_ACCESS_KEY: YWRtaW4= # admin
  AWS_SECRET_ACCESS_KEY: YWRtaW4xMjM= # admin123

