apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-coordinator-config
  namespace: query-engine
data:
  access-control.properties: |
    access-control.name=ranger

  # Configuração Hadoop / S3
  config.properties: |
    coordinator=true
    node-scheduler.include-coordinator=true
    http-server.http.port=8080
    discovery.uri=http://localhost:8080
    query.max-memory=2GB
    query.max-memory-per-node=1GB
    catalog.management=dynamic

  log.properties: |
    com.example=DEBUG

  node.properties: |
    node.environment=production
    node.id=trino-coordinator
    node.data-dir=/data/trino

  jvm.config: |
    -server
    -Xmx2G
    -XX:InitialRAMPercentage=80
    -XX:MaxRAMPercentage=80
    -XX:G1HeapRegionSize=32M
    -XX:+ExplicitGCInvokesConcurrent
    -XX:+ExitOnOutOfMemoryError
    -XX:+UseG1GC
    -XX:ReservedCodeCacheSize=256M
    -XX:PerMethodRecompilationCutoff=10000
    -XX:PerBytecodeRecompilationCutoff=10000
    -Djdk.attach.allowAttachSelf=true
    -Djdk.nio.maxCachedBufferSize=2000000
    -XX:+UnlockDiagnosticVMOptions
    -XX:G1NumCollectionsKeepPinned=10000000