apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ranger-solr-pvc
  namespace: data-government
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ranger-solr
  namespace: data-government
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ranger-solr
  template:
    metadata:
      labels:
        app: ranger-solr
    spec:
      containers:
      - name: ranger-solr
        image: apache/ranger-solr:2.5.0
        ports:
        - containerPort: 8983
        volumeMounts:
        - name: solr-data
          mountPath: /var/solr
      volumes:
      - name: solr-data
        persistentVolumeClaim:
          claimName: ranger-solr-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ranger-solr
  namespace: data-government
spec:
  selector:
    app: ranger-solr
  ports:
  - protocol: TCP
    port: 8983
    targetPort: 8983