apiVersion: v1
kind: ConfigMap
metadata:
  name: ranger-admin-config
  namespace: data-government
data:
  RANGER_DB_TYPE: "postgres"
  DB_HOST: "postgres.database.svc.cluster.local"
  DB_ROOT_USER: "admin"
  DB_ROOT_PASSWORD: "admin"
  XAAUDIT_SOLR_URL: "http://ranger-solr:8983/solr/ranger_audits"

  install.properties: |
    #
    # This file provides a list of the deployment variables for the Policy Manager Web Application
    #

    PYTHON_COMMAND_INVOKER=python3
    RANGER_ADMIN_LOG_DIR=/var/log/ranger
    RANGER_PID_DIR_PATH=/var/run/ranger
    DB_FLAVOR=POSTGRES
    SQL_CONNECTOR_JAR=/usr/share/java/postgresql.jar
    RANGER_ADMIN_LOGBACK_CONF_FILE=/opt/ranger/admin/ews/webapp/WEB-INF/classes/conf/logback.xml

    db_root_user=admin
    db_root_password=admin
    db_host=postgres.database.svc.cluster.local

    db_name=ranger
    db_user=rangeradmin
    db_password=rangerR0cks!

    postgres_core_file=db/postgres/optimized/current/ranger_core_db_postgres.sql
    postgres_audit_file=db/postgres/xa_audit_db_postgres.sql
    mysql_core_file=db/mysql/optimized/current/ranger_core_db_mysql.sql
    mysql_audit_file=db/mysql/xa_audit_db.sql

    rangerAdmin_password=rangerR0cks!
    rangerTagsync_password=rangerR0cks!
    rangerUsersync_password=rangerR0cks!
    keyadmin_password=rangerR0cks!


    audit_store=solr
    audit_solr_urls=http://ranger-solr.data-government.svc.cluster.local:8983/solr/ranger_audits
    audit_solr_collection_name=ranger_audits

    policymgr_external_url=http://ranger-admin:6080
    policymgr_http_enabled=true

    unix_user=ranger
    unix_user_pwd=ranger
    unix_group=ranger

    # Following variables are referenced in db_setup.py. Do not remove these
    oracle_core_file=
    sqlserver_core_file=
    sqlanywhere_core_file=
    cred_keystore_filename=

    # #################  DO NOT MODIFY ANY VARIABLES BELOW #########################
    #
    # --- These deployment variables are not to be modified unless you understand the full impact of the changes
    #
    ################################################################################
    XAPOLICYMGR_DIR=$PWD
    app_home=$PWD/ews/webapp
    TMPFILE=$PWD/.fi_tmp
    LOGFILE=$PWD/logfile
    LOGFILES="$LOGFILE"

    JAVA_BIN='java'
    JAVA_VERSION_REQUIRED='1.8'

    ranger_admin_max_heap_size=1g
    #retry DB and Java patches after the given time in seconds.
    PATCH_RETRY_INTERVAL=120
    STALE_PATCH_ENTRY_HOLD_TIME=10

    hadoop_conf=
    authentication_method=UNIX