apiVersion: v1
kind: Namespace
metadata:
  name: storage

---
apiVersion: v1
kind: Namespace
metadata:
  name: catalogue

---
apiVersion: v1
kind: Namespace
metadata:
  name: query-engine

---
apiVersion: v1
kind: Namespace
metadata:
  name: database