apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-config
  namespace: catalogue
data:
  # Configuração Hadoop / S3
  core-site.xml: |

    <configuration>
      <!-- S3A Configuration -->
      <property>
        <n>fs.s3a.endpoint</n>
        <value>http://minio.storage.svc.cluster.local:9000</value>
      </property>
      
      <property>
        <n>fs.s3a.access.key</n>
        <value>${MINIO_ADMIN_ACCESS_KEY}</value>
      </property>
      
      <property>
        <n>fs.s3a.secret.key</n>
        <value>${MINIO_ADMIN_SECRET_KEY}</value>
      </property>
      
      <property>
        <n>fs.s3a.path.style.access</n>
        <value>true</value>
      </property>
      
      <property>
        <n>fs.s3a.connection.ssl.enabled</n>
        <value>false</value>
      </property>
      
      <property>
        <n>fs.s3a.impl</n>
        <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
      </property>
      
      <!-- Default FS Configuration -->
      <property>
        <n>fs.defaultFS</n>
        <value>file:///</value>
      </property>
    </configuration>

  hive-site.xml: |
      <configuration>
        <!-- Database Configuration -->
        <property>
          <name>javax.jdo.option.ConnectionURL</name>
          <value>jdbc:postgresql://postgres.database.svc.cluster.local:5432/metastore</value>
        </property>
        
        <property>
          <name>javax.jdo.option.ConnectionDriverName</name>
          <value>org.postgresql.Driver</value>
        </property>
        
        <property>
          <name>javax.jdo.option.ConnectionUserName</name>
          <value>${METASTORE_DB_USER}</value>
        </property>
        
        <property>
          <name>javax.jdo.option.ConnectionPassword</name>
          <value>${METASTORE_DB_PASSWORD}</value>
        </property>

        <!-- S3/MinIO Configuration -->
        <property>
          <name>fs.s3a.endpoint</name>
          <value>http://minio.storage.svc.cluster.local:9000</value>
        </property>
        
        <property>
          <name>fs.s3a.access.key</name>
          <value>${MINIO_ADMIN_ACCESS_KEY}</value>
        </property>
        
        <property>
          <name>fs.s3a.secret.key</name>
          <value>${MINIO_ADMIN_SECRET_KEY}</value>
        </property>
        
        <property>
          <name>fs.s3a.path.style.access</name>
          <value>true</value>
        </property>
        
        <property>
          <name>fs.s3a.impl</name>
          <value>org.apache.hadoop.fs.s3a.S3AFileSystem</value>
        </property>

        <!-- Warehouse Configuration 
        <property>
          <name>hive.metastore.warehouse.dir</name>
          <value>s3a://warehouse/</value>
        </property> -->
        
        <property>
          <name>hive.metastore.uris</name>
          <value>thrift://hive-metastore.metastore.svc.cluster.local:9083</value>
        </property>
        
        <!-- Schema Validation -->
        <property>
          <name>hive.metastore.schema.verification</name>
          <value>false</value>
        </property>
        
        <property>
          <name>datanucleus.schema.autoCreateAll</name>
          <value>true</value>
        </property>
        
        <property>
          <name>hive.metastore.schema.verification.record.version</name>
          <value>false</value>
        </property>
      </configuration>