apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      initContainers:
      - name: init-hive-schema
        image: hive-de-infra:1
        command:
          - "bash"
          - "-c"
          - |
            echo 'Aguardando PostgreSQL...'
            sleep 15
            echo "Usando usuario=${PG_USERNAME}"
            echo "URL=jdbc:postgresql://postgres.database.svc.cluster.local:5432/metastore"
            if ! /opt/hive/bin/schematool -dbType postgres -userName ${PG_USERNAME} -passWord ${PG_PASSWORD} \
                -url jdbc:postgresql://postgres.database.svc.cluster.local:5432/metastore -driver org.postgresql.Driver -info; then
              echo 'Inicializando schema do Hive Metastore...'
              /opt/hive/bin/schematool -initSchema -dbType postgres -userName ${PG_USERNAME} -passWord ${PG_PASSWORD} \
                -url jdbc:postgresql://postgres.database.svc.cluster.local:5432/metastore -driver org.postgresql.Driver --verbose
            else
              echo 'Schema do Hive Metastore já existe'
            fi
        envFrom:
        - secretRef:
            name: hive-credentials
      containers:
      - name: hive-metastore
        image: hive-de-infra:1
        command: 
          - "/opt/hive/bin/hive"
          - "--service"
          - "metastore"
        ports:
        - containerPort: 9083
        env:
        - name: HADOOP_OPTS
          value: >-
            -Djavax.jdo.option.ConnectionUserName=$(PG_USERNAME)
            -Djavax.jdo.option.ConnectionPassword=$(PG_PASSWORD)
            -Dfs.s3a.access.key=$(MINIO_ADMIN_ACCESS_KEY)
            -Dfs.s3a.secret.key=$(MINIO_ADMIN_SECRET_KEY)

        envFrom:
        - secretRef:
            name: hive-credentials
        volumeMounts:
        - name: hive-config
          mountPath: /opt/hive/conf

      volumes:
      - name: hive-config
        configMap:
          name: hive-config
