apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:
      containers:
      - name: hive-metastore
        image: hive-de-infra:1
        command:
            - "bash"
            - "-c"
            - |
              echo 'Aguardando PostgreSQL...'
              sleep 15
              if ! /opt/hive/bin/schematool -dbType postgres -userName $(pg_username) -passWord $(pg_password) -info > /dev/null 2>&1; then
                echo 'Inicializando schema do Hive Metastore...'
                /opt/hive/bin/schematool -initSchema -dbType postgres -userName $(pg_username) -passWord $(pg_password) --verbose
              else
                echo 'Schema do Hive Metastore já existe'
              fi
              echo 'Iniciando Hive Metastore...'
              /opt/hive/bin/hive --service metastore
        ports:
        - containerPort: 9083
        env:
        - name: SERVICE_OPTS
          value: >-
            -Djavax.jdo.option.ConnectionUserName=admin
            -Djavax.jdo.option.ConnectionPassword=admin

        - name: HADOOP_OPTS
          value: >-
            -Dfs.s3a.access.key=$(minio_admin_access_key)
            -Dfs.s3a.secret.key=$(minio_admin_secret_key)
        envFrom:
        - secretRef:
            name: hive-credentials


        volumeMounts:
        - name: hive-config
          mountPath: /opt/hive/conf
      volumes:
      - name: hive-config
        configMap:
          name: hive-config

